import type { Metadata } from "next";
import "./_styles/globals.css";
import "./_styles/buttons.css";
import Navbar from "./_components/Navbar";
import { CartProvider } from "./_components/common/Cart";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
